---
name: Validate PR
# description: Validate a pull request.

on:
    pull_request:
        types:
            - opened
            - edited
            - reopened

permissions:
    pull-requests: read

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Validate PR title
              uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
